t/refaddr.t

"use warnings" provokes a warning but "local $^X" does not silence it,
whereas "no warnings" does.  b810db1350e68a added "use warnings"
introducing the problem.

Silence a warning properly

---

ListUtil.xs

When `List::Util` is built as part of core, `-Wunused-vars` gets set, and
gcc complains about these variables.
They were added by the commit 8630ea87 on 2013-08-01, but never used.

Remove unused variables in pairmap()

---

Makefile.PL
lib/List/Util.pm
lib/List/Util/XS.pm
lib/Scalar/Util.pm

Hi Paul,
This adds the min perl version to the dist's metadata, via `MIN_PERL_VERSION` in `Makefile.PL`.
And I added `use warnings` to the modules that didn't already have it.
Cheers,
Neil

Addresses the two outstanding Kwalitee issues

---

ListUtil.xs

dMULTICALL no longer declares this variable

Don't reference newsp on >= 5.23.8 (RT#112312)

---

ListUtil.xs

MSVC is a real pain... here's a patch to fix another inline variable declaration.

Fix inline variable declaration for non-C99 compilers

---

lib/List/Util.pm

This PR merely documents the current behaviour (which treats all `NaN` values as equal, because it's using a hash to detect uniqueness of string representation).
It's possible that some people would prefer a strict IEEE approach of treating any `NaN` value as unequal to all other `NaN` values (including itself); or even an approach that treats `NaN` values as unequal iff their payloads differ. My guess is that the current behaviour offers least surprise for most people.

Document the behaviour of uniqnum() on NaN

---

ListUtil.xs

C++11 changed from earlier versions to require space between the end of
a string literal and a macro, so that a feature can unambiguously be
added to the language.  Starting in g++ 6.2, the compiler emits a
deprecation warning when there isn't a space (presumably so that future
versions can support C++11).
Code and modules included with the Perl core need to be compilable using
C++.  This is so that perl can be embedded in C++ programs. (Actually,
only the hdr files need to be so compilable, but it would be hard to
test that just the hdrs are compilable.)  So we need to accommodate
changes to the C++ language.

ListUtil: Remove impediment to compiling under C++11

---

lib/List/Util.pm

Footnotes for docs as discussed in IRC.

footnote that outer @_ can be accessed in some blocks, but shouldn't be

---

t/product.t
t/sum.t
t/uniq.t

It is better to run tests instead of skipping them.

Fix tests to work also on Perl 5.6.2

---

ListUtil.xs
t/exotic_names.t

This includes unicode and binary names.  Patches are primarily taken from Sub::Name.

Fix set_subname with exotic names

---

ListUtil.xs
lib/List/Util.pm
t/head-tail.t

`head( $n, @list )` grabs the first `$n` elements from `@list`, or if `$n` is
negative, all but the last `$n` elements.
`tail( $n, @list )` grabs the last `$n` elements from `@list`, or if `$n` is
negative, all but the first `$n elements.
These are useful if you need to slice a list and do not want to assign
it to a temporary array. For example, as part of a map/grep/sort/etc...
chain.
---
With this setup, a slice() sub would be pretty trivial. If this stuff isn't appropriate for List::Util, I could make them into their own dist.

add head() and tail() subs

---

lib/Scalar/Util.pm

Hello,
"is is" is just a typo, I tried fixing it. Hope this helps.
Regards

fix typo in doc (sentence is still very long though...)

---

ListUtil.xs
lib/Sub/Util.pm
t/subname.t

Return `__ANON__` as the package name if the stash has been deleted.

Fix segfaults in (set_)subname with deleted stashes

---

ListUtil.xs
t/uniq.t

- Call SvNV on scalars with no numeric flags set (this sets SVf_IOK/SVf_UOK as appropriate)
- Use 15 digits of precision for NVs (matches Perl's default stringification)

Fix uniqnum for large floats and numeric strings

---

ListUtil.xs

Turns out long-double perls' `SvNV()` macro doesn't set the integer
flags even if the value is an integer.  Use `SvIV()` instead, which
appears to be doing the right thing for normal, long and quad doubles.

Fix uniqnum on large stringified integers on long- and quad-double perls

---

ListUtil.xs
Makefile.PL
t/uniq.t

Using sprintf "%.15g" as the value to compare does not maintain the full
accuracy of floating point numbers.  Rather than 15, use a precision
value based on the accuracy the current platform can represent.
Also add some special cases: treat 0 and -0.0 as equivalent, and NaNs
are compared based on the platform's stringification of them.
Additionally, sprintf may not be able to accurately represent some
floating point numbers, no matter how many digits are given.  If the
numbers are outside the IV/UV range, they don't need to be compared to
anything other than other floats, so we can use a totally different
format for the unique string.  Use their raw bytes, as this is the
easiest and fastest.
Fixes RT#130935, RT#130302, RT#130277

increase accuracy of uniqnum

---

t/reductions.t
t/sample.t

done_testing was added in Test::More 0.88, and isn't available on stock
perls older than 5.10.1.  Adding a dependency on a newer Test::More
would introduce a dependency loop on those older perls.

avoid done_testing for compatibility with old perl

---

t/sample.t
t/shuffle.t

Rather than testing the output of shuffle or sample with a predictable
$RAND resulting in a specific pattern, run the function multiple times
and verify it gives the same results.  This means the test doesn't have
to rely on the specific implementation of the functions, since there are
many ways they could be written.  Users also shouldn't be relying on a
given random function giving identical results across versions or
systems.

test predictable $RAND giving consistent results, not predefined results

---

ListUtil.xs
Makefile.PL

First up:
The changes I've made to the Makefile.PL have nothing to do with this topic.
They simply remove stuff that I never intended to be included in https://github.com/Dual-Life/Scalar-List-Utils/pull/91
That "stuff" was really only relevant to my own systems and was there as an additional check that some brainfart of mine was not setting NV_MAX_PRECISION greater than necessary - which is something that the test suite would not detect. (Should the test suite check be checking for this ?)
I'm quite happy to reinstate that "stuff" if it's requested, though there would then need to be some modification of it.
For example, whilst it's true, on my machines, that an NV_MAX_PRECISION value of 36 implies an nvtype of __float128, there are some architectures where the value of 36 would imply …

Fix uniqnum for mingw-built Win32 perls that don't define __USE_MINGW_ANSI_STDIO

---

Makefile.PL

Properly list Test::More as a test dependency rather than a runtime
dependency.  This requires adding some code to cope with older versions
of EUMM that don't understand TEST_REQUIRES.

move Test::More to be a test dependency

---

ListUtil.xs
Makefile.PL

In ListUtil.xs, I inserted an "#if IVSIZE != NVSIZE" block into uniqnum().
That block is needed for the case where NV is doubledouble - but it so happens that all other configurations where IVSIZE != NVSIZE" are handled more efficiently by that same approach.
Therefore, rather than create that block as "#ifdef NV_IS_DOUBLEDOUBLE",  I've expanded it to handle all cases where IVSIZE != NVSIZE.
At the end of this post, I'll include the benchmark script which (hopefully) demonstrates the benefit of this approach.
Having done that, it then meant that the one occurrence of NV_MAX_PRECISION was always 20.
Hence, we're able to replace that occurrence of NV_MAX_PRECISION with a hard-coded "20", and remove the calculations of NV_MAX_PRECISION from the Makefile.PL.
I suppose one annoyance with this …

Improve uniqnum's handling of configurations where IVSIZE != NVSIZE

---

ListUtil.xs
t/uniq.t

Also fixes a problem I came across with DoubleDouble NV types.
The problem was, that with this NV type, the DoubleDouble pair (x, 0.0) would be considered distinct from the DoubleDouble pair (x, -0.0).
Clearly, they should be regarded as duplicates of each other because x + 0.0 == x - 0.0 for all non-NaN x.
The main fix, however, is for perls whose nvsize == ivsize == 8 that were built with older MS compilers like VC++ 2010 (aka Visual C++ 10.0, among other things).
This was the issue that for many large IV/UV values that could also be exactly represented by an NV,
the NV and the IV/UV were not being recognized as duplicates of each other.
To fix it, I was forced to a solution that turned out to be so elegant and efficient, that I applied it "across the board" for all perls whose nvsize …

Fix uniqnum for less recent Microsoft Compilers

---

t/uniqnum.t

Check specifically for absence of NOK flag on perl 5.6 when looking at IOK or UOK in case of IVNV or UVNV dualvars

Fix uniqnum for IVNV or UVNVs on Perl 5.6

---

ListUtil.xs
lib/List/Util.pm
t/uniq.t

To smooth over most of the complications of `uniqnum()` when you know your numbers should be well-behaved integers.

Add a `uniqint()` function

---

ListUtil.xs

Perl_ceil was added in perl 5.8.3, not 5.8.0

---

ListUtil.xs
t/uniqnum.t

Some of this trailing whitespace first appeared in 1.55-TRIAL; the
balance was pre-existing.

Eliminate trailing whitespace

---

ListUtil.xs
lib/Scalar/Util.pm

Hence remove all the conditional logic and documentation for supporting
earlier versions of Perl which did not have weak references.

The minimum Perl version is v5.6.0, which supports weak references

---

ListUtil.xs

The code had been handling the return value from hv_store_ent incorrectly.
hv_store_ent returns NULL if the store didn't happen (a tied hash), or if
the store operation failed - in other words, it returns true *if* it took
ownership of a reference to the stored value, false if not. This entire API
is somewhat clunky and error prone, and also somewhat makework, as store
never returns NULL on a valid untied hash - it will always succeed, or
croak if memory allocation fails.
This is a regression introduced in 2016 as part of commit a50a854f07ccc665:
Fix %DB::sub for subs with non-Latin1 characters
That commit refactored the code from hv_store to hv_store_ent - a sensible
choice, as the latter API is more efficient - but introduced two small
errors not present in the previous code - inverting …

Correct refcount handling on hv_store_ent to PL_DBsub in set_subname

---

ListUtil.xs
t/undefined-block.t

The pair* functions weren't checking the sv_2cv return value at all,
while the rest were only checking for not a subroutine, not for
references to undefined subs.

Fix segfaults when undefined subroutine passed to block-taking subs

---

t/pair.t

This ensures that changes to one won't impact the test for the other.
It also prepares for a potential future where the modules are split into
separate dists.  This also makes it easier to port tests to
List::Util::PP, which wants to avoid all direct dependencies on
Scalar::Util.
This change is admittedly mainly to make it easier for me to maintain List::Util::PP.

avoid using Scalar::Util functions in List::Util tests

---

ListUtil.xs
lib/List/Util.pm
lib/List/Util/XS.pm
lib/Scalar/Util.pm
lib/Sub/Util.pm

When building blead Scalar-List-Utils 1.60 throws warnings:
ListUtil.xs: In function ‘XS_List__Util_zip’:
ListUtil.xs:1619:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if(av_count(av) > len)
^
ListUtil.xs:1624:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if(av_count(av) < len)
^
ListUtil.xs:1639:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
SV *item = (i < av_count(lists[listi])) ?
^
ListUtil.xs:1658:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
SV *item = (i < av_count(lists[listi])) ?
^
Perl_av_count is defined to return a Size_t, which fits its
purpose of returning the number of items in the array which
cannot be …

Fix Perl Issue #19429: Scalar-List-Utils: fix signed/unsigned comparison warnings

---

t/tainted.t

Hi,
I'm working on changes to the Configure script, to make it easy to build a perl that doesn't have taint support.
This PR changes `t/taint.t` to skip all tests if being installed on such a perl.
Cheers,
Neil

Skip the tainted tests if your perl was built without taint support

---

lib/Scalar/Util.pm

Hi Team,
I noticed typo in the pod section for is_weak(), where it says it is equivalent to builtin::isweak rather builtin::is_weak.
Please review the change.
Many Thanks.
Best Regards,
Mohammad

Fixed typo in isweak() pod section.

---

t/exotic_names.t

This fixes the only EBCDIC_ failure in the test suite for this module.

Generalize exotic_names.t to work for EBCDIC

---

.github/workflows/testsuite.yml

In addition to Travis CI run integrations
tests on GitHub using Perl 5.6 to 5.32
and a basic test on macOS and Windows.
Note that a fast a simple test is run using
a stock ubuntu docker image from GitHub.
Other jobs are only triggered on success.

Add basic GitHub CI workflow

---

.github/workflows/testsuite.yml

Remove macOS and windows pipeline as they are
discouraged by GitHub as they consume more ressource and brings a low value.
Use the `perl-actions/perl-versions@v1` pipeline to use a dynamic list of current Perl versions.

Adjust testsuite for perl-versions

---

ListUtil.xs
lib/Scalar/Util.pm

On Perl 5.40 and above, use the various `builtin::` functions to provide those in `Scalar::Util`, avoiding the need for our own custom xsubs in that case

Use builtin:: functions where available

---

t/uniqnum.t

If infinities are not working, make sure we fail after a few tries rather than looping infinitely to find infinity. 10 iterations is arbitrary -- 1 is likely enough in most cases.

Don't loop forever in uniqnum.t

---

t/uniqnum.t

The test `!$nanish != $NaN` doesn't make much sense: It checks whether a boolean (effectively 0 or 1) is not equal to `$NaN`, which is always true. (Also, we know `$nanish != 0` from the preceding test, so `!$nanish` could be hardcoded as 0 here.)
Instead test whether `$NaN` correctly round-trips through strings, i.e. whether `$nanish` behaves like a proper NaN again (being non-equal to both the original `$NaN` and itself).

fix precedence issue in uniqnum.t

---

lib/Scalar/List/Utils.pm

Various tools expect to be able to translate distribution names to module names. That isn't always true, but it's helpful when it can be.
Add a Scalar::List::Utils module to match the dist name, including links to the other included modules.

add Scalar::List::Utils module to match dist name

---

t/stack-corruption.t
t/sum.t
t/uniq.t
t/uniqnum.t

The fix follows Zefram's suggestion from
https://www.nntp.perl.org/group/perl.perl5.porters/2012/05/msg186846.html
> On older perls, however, $] had a numeric value that was built up using
> floating-point arithmetic, such as 5+0.006+0.000002.  This would not
> necessarily match the conversion of the complete value from string form
> [perl #72210].  You can work around that by explicitly stringifying
> $] (which produces a correct string) and having *that* numify (to a
> correctly-converted floating point value) for comparison.  I cultivate
> the habit of always stringifying $] to work around this, regardless of
> the threshold where the bug was fixed.  So I'd write
>
>     use if "$]" >= 5.014, warnings => "non_unicode";
This ensures that the comparisons will still work when Perl's major …

fix string comparisons with $] to use numeric comparison instead

---

ListUtil.xs
lib/Scalar/Util.pm
t/isvstring.t

On perl 5.6, the isvstring function would not allow itself to be called or exported. This behavior is annoying to implement, and forces loading Exporter::Heavy in all cases.
Instead, isvstring can just always return false on perl 5.6. This is an accurate behavior, as nothing on perl 5.6 is a vstring. And the odds of anyone caring about this specific behavior on a prehistoric version of perl is almost certainly 0.

always allow isvstring to be used
